const ProjectCategories = {
  Arts: "Arts",
  Film: "Film",
  Food: "Food",
  Retail: "Retail",
  NightLife: "Night Life",
  Technology: "Technology",
  Games: "Games",
  Music: "Music",
  Other: "Other",
  // AutoServices: "AutoServices",
  // ConsultingServices: "ConsultingServices",
  // Catering: "Catering",
  // ChildCare: "ChildCare",
  // CleaningServices: "CleaningServices",
  // Contractor : "Contractor",
  // Dentist: "Dentist",
  // Electrical: "Electrical",
  // EventVenue: "EventVenue", 
  // Florist: "Florist",
  // HealthWellness: "HealthWellness",
  // Healthcare: "Healthcare",
  // HomeImprovement: "HomeImprovement",
  // HVAC: "HVAC",
  // Insurance: "Insurance",
  // LawnCare: "LawnCare",
  // Legal: "Legal",
  // Locksmith: "Locksmith",
  // MovingStorage: "MovingStorage",
  // Hospitality: "Hospitality",
  // NonProfit: "NonProfit",
  // PestControl: "PestControl",
  // PetGrooming: "PetGrooming",
  // Photography: "Photography",
  // Plumber: "Plumber",
  // RealEstate: "RealEstate",
  // Roofing: "Roofing",
  // Salon: "Salon",
  // Veterinarian: "Veterinarian",
};

type ProjectCategory = typeof ProjectCategories;

export { ProjectCategories };
export type { ProjectCategory };
